/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class getFunction */

#ifndef _Included_getFunction
#define _Included_getFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     getFunction
 * Method:    Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_getFunction_Init
  (JNIEnv *, jobject, jint);

/*
 * Class:     getFunction
 * Method:    Exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_getFunction_Exit
  (JNIEnv *, jobject);

/*
 * Class:     getFunction
 * Method:    FaceRecog
 * Signature: ([BLPFD_FACE_DETECT;IS)I
 */
JNIEXPORT jint JNICALL Java_getFunction_FaceRecog
  (JNIEnv *, jobject, jbyteArray, jobject, jint, jshort);

/*
 * Class:     getFunction
 * Method:    GetFeature
 * Signature: ([BLPFD_FACE_DETECT;Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_GetFeature
  (JNIEnv *, jobject, jbyteArray, jobject, jstring, jshort);

/*
 * Class:     getFunction
 * Method:    FeatureMatching
 * Signature: (S[BS[B)I
 */
JNIEXPORT jint JNICALL Java_getFunction_FeatureMatching
  (JNIEnv *, jobject, jshort, jbyteArray, jshort, jbyteArray);

/*
 * Class:     getFunction
 * Method:    StoreFeature
 * Signature: (IS[B)I
 */
JNIEXPORT jint JNICALL Java_getFunction_StoreFeature
  (JNIEnv *, jobject, jint, jshort, jbyteArray);

/*
 * Class:     getFunction
 * Method:    DeleteFeature
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_getFunction_DeleteFeature
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     getFunction
 * Method:    MatchFeature
 * Signature: (IIS[BS[I[S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_MatchFeature
  (JNIEnv *, jobject, jint, jint, jshort, jbyteArray, jshort, jintArray, jshortArray);

/*
 * Class:     getFunction
 * Method:    ResetDataBase
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_getFunction_ResetDataBase
  (JNIEnv *, jobject, jint);

/*
 * Class:     getFunction
 * Method:    DeleteDataBase
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_getFunction_DeleteDataBase
  (JNIEnv *, jobject, jint);

/*
 * Class:     getFunction
 * Method:    AddDataBase
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_getFunction_AddDataBase
  (JNIEnv *, jobject, jint);

/*
 * Class:     getFunction
 * Method:    ChangeFeature
 * Signature: (IIS[B)I
 */
JNIEXPORT jint JNICALL Java_getFunction_ChangeFeature
  (JNIEnv *, jobject, jint, jint, jshort, jbyteArray);

/*
 * Class:     getFunction
 * Method:    AgrRecogImg
 * Signature: ([BLPFD_AGR_DETECT;S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_AgrRecogImg
  (JNIEnv *, jobject, jbyteArray, jobject, jshort);

/*
 * Class:     getFunction
 * Method:    SmileRecogImg
 * Signature: ([BLPFD_SMILE_DETECT;S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_SmileRecogImg
  (JNIEnv *, jobject, jbyteArray, jobject, jshort);

/*
 * Class:     getFunction
 * Method:    DirectRecogImg
 * Signature: ([BLPFD_DIRECT_DETECT;S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_DirectRecogImg
  (JNIEnv *, jobject, jbyteArray, jobject, jshort);

/*
 * Class:     getFunction
 * Method:    BlinkRecogImg
 * Signature: ([BLPFD_BLINK_DETECT;S)I
 */
JNIEXPORT jint JNICALL Java_getFunction_BlinkRecogImg
  (JNIEnv *, jobject, jbyteArray, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
